### ISSUE TITLE
Questions about DownloadAsync 

### ISSUE THREAD

**Issue by blackWins** [EasyAbp/FileManagement#114]
https://github.com/EasyAbp/FileManagement/blob/f0abb9545771a9d6fe7f4ff2aa0a42f388063a08/src/EasyAbp.FileManagement.Application/EasyAbp/FileManagement/Files/FileAppService.cs#L339-L354

Why not consider using the token directly to get the resource ID.

Replace `Task CheckTokenAsync(token, id)`  with `Task<Guid> GetResourceIdByToken(token)` 
https://github.com/EasyAbp/FileManagement/blob/f0abb9545771a9d6fe7f4ff2aa0a42f388063a08/src/EasyAbp.FileManagement.Domain/EasyAbp/FileManagement/Files/LocalFileDownloadProvider.cs#L51-L51

**Comment by gdlcf88** [comment]
Both options are fine, and we won't make any unnecessary breaking changes.
