### ISSUE TITLE
Instructions to add from Nuget

### ISSUE THREAD

**Issue by reidatlokblok** [EasyAbp/FileManagement#117]
It is not very clear how to add this module from source or from nuget as someone new to the abp and easyabp platform.  Some pointers would be helpful.

Added all from Nuget, no source:

1. it is easy to add easyabp.filemanagement using the abphelper or abphelper.gui however it does not add the ui only the module.  I completed this step without issue, created and ran the db migration and was able to see and add permissions to users.
2. to add a ui, i added easyabp.filemanagement.blazor.server AND added [DependsOn(typeof(FileManagementBlazorServerModule) to the blazor server module.  The "File" menu then showed up for users with permissions but the page is empty - message in the view instead says "Sorry, there's nothing at this address." and the address is "https://localhost:44371/FileManagement/Files/File".  I believe that the blob storage needs to get setup??  However, it is not clear how to do this from the instructions in the github doc. 

Any next steps for completing setup using only nuget package would be appreciated.  Once this is working I would like to try from source but the instructions there are not clear for a newbie to abp.io framework.  One thing at a time...

**Comment by blackWins** [comment]
@reidatlokblok Blazor UI is not developed yet or you can provide PR to improve Blazor UI

**Comment by reidatlokblok** [comment]
Thank you for the response.  The MVC version is working.
