### ISSUE TITLE
local file download provider中的 url需要修改

### ISSUE THREAD

**Issue by tkezyo** [EasyAbp/FileManagement#27]
https://github.com/EasyAbp/FileManagement/blob/517d8790963f1443458bc175211174adbebc0872/src/EasyAbp.FileManagement.Domain/EasyAbp/FileManagement/Files/LocalFileDownloadProvider.cs#L17

修改为api/file-management/file/{0}/download

**Comment by gdlcf88** [comment]
Thanks, @tkezyo :)
