### ISSUE TITLE
API报错

### ISSUE THREAD

**Issue by buyihly** [EasyAbp/FileManagement#28]
运行起来后测试API时报400错误，日志显示
[16:52:29 ERR] The required antiforgery cookie ".AspNetCore.Antiforgery.wFLV_IZKzC0" is not present.
请问这个该怎么样解决呢？谢谢！
IdentityServer已经运行的了。

**Comment by slarkerino** [comment]
一般cookie清了就好。要是微服务环境的话最好就把antiforgery都禁用了

**Comment by gdlcf88** [comment]
https://docs.abp.io/en/abp/latest/CSRF-Anti-Forgery
