### ISSUE TITLE
online demo, There are no file upload or create directory  buttons

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/FileManagement#29]
online demo : https://file.samples.easyabp.io is broken.

The file menu does not have ( file upload or create directory)  buttons.
As In the picture
![Files](https://github.com/EasyAbp/FileManagement/blob/master/docs/images/Files.png)

**Comment by hueifeng** [comment]
@mrs01dev In Chinese, this seems to be normal, and I didn't find anything unusual. It seems to have something to do with localization cc @gdlcf88 

![image](https://user-images.githubusercontent.com/34702552/110736505-c0ed8a00-8266-11eb-9247-16a6980bc832.png)

![image](https://user-images.githubusercontent.com/34702552/110736643-feeaae00-8266-11eb-96ba-cb85c5e4e394.png)

**Comment by mrs01dev** [comment]
It is working, but (strange methodology non intuitive )
When you open file menu
[https://github.com/mrs01dev/FileManagement/blob/master/docs/images/image_2021-03-10_210943.png](url)
So:
 

- I must type default 
- select  OwnerUserId

[https://github.com/mrs01dev/FileManagement/blob/master/docs/images/image_2021-03-10_210758.png](url)

- press search button
- after that there is button  with text ("edit" should be "upload" ),[https://github.com/mrs01dev/FileManagement/blob/master/docs/images/image_2021-03-10_211335.png](url)
- Thanks.

**Comment by gdlcf88** [comment]
> * I must type default
> * select  OwnerUserId

The default index page is for generic business scenarios, you can override it or create another better page yourself.

I have fixed the localization item `UploadFile` and release the new version 1.3.2.
