### ISSUE TITLE
FileManagement在线演示不能看

### ISSUE THREAD

**Issue by hqmlz** [EasyAbp/FileManagement#48]
FileManagement在线演示不能看。

**Comment by gdlcf88** [comment]
@hueifeng Could you please fix the online demo site?

**Comment by hqmlz** [comment]
@gdlcf88  Excuse me, is there an overall structure document description?

**Comment by hqmlz** [comment]
@gdlcf88 For example, if I want to execute the API interface alone, how should I execute it?
