### ISSUE TITLE
下载token验证重写

### ISSUE THREAD

**Issue by liaozb** [EasyAbp/FileManagement#62]
https://github.com/EasyAbp/FileManagement/blob/30688763f667c79129f8fa55cc81450c9e5ed874/src/EasyAbp.FileManagement.Application/EasyAbp/FileManagement/Files/FileAppService.cs#L506

能否改用IFileDownloadProvider 调用，方便重写。

**Comment by gdlcf88** [comment]
No, the `CheckTokenAsync` method is unique to LocalFileDownloadProvider. It was designed to implement local download.

You can create different APIs for different providers.
