### ISSUE TITLE
是否考虑url的token授权支持其它方式？

### ISSUE THREAD

**Issue by git102347501** [EasyAbp/FileManagement#64]
由于url中放置token认证，会导致资源下载每次url不唯一，前端是根据url来缓存资源的，这样缓存会持续失效下载重复资源
是否可以针对此问题，进行其它形式的鉴权？

**Comment by baiqiaw** [comment]
富文本中上传图片，图片路径是和富文本中的HTML代码一起保存的，这种情况下放置token认证是否合理？

**Comment by gdlcf88** [comment]
The default `LocalFileDownloadProvider` is not good for large files. You should customize `IFileDownloadProvider` yourself for complex scenarios.
