### ISSUE TITLE
Blazor没有默认的界面吗

### ISSUE THREAD

**Issue by wozpren** [EasyAbp/FileManagement#92]
只有SamplePageMessage一行字
翻源码好像也没有

**Comment by gdlcf88** [comment]
EasyAbp currently only provides the management UI for MVC. Moreover, even the MVC UI is not well-completed, which is limited by the multi-frontend framework of ABP, making it difficult for us to invest in developing efforts for a certain front-end framework. 

You can refer to the MVC version of the management UI to implement your own Blazor implementation.
